/**
 * TypeScript wrapper for Thalora Web Browser WASM module
 *
 * Provides a high-level, type-safe API for browser automation,
 * AI memory management, and fingerprint spoofing.
 */

// Import WASM module types (generated by wasm-pack)
import type {
  ThaloraBrowser as WasmThaloraBrowser,
  WasmStorage as WasmStorageType,
  WasmAIMemory as WasmAIMemoryType,
  WasmFingerprint as WasmFingerprintType,
  WasmDOM as WasmDOMType,
  WasmReadability as WasmReadabilityType,
  WasmCssProcessor as WasmCssProcessorType,
  WasmLayoutEngine as WasmLayoutEngineType,
  WasmJsEngine as WasmJsEngineType,
  WasmPageProcessor as WasmPageProcessorType,
  WasmScrapedData,
  WasmLink,
  WasmImage,
  WasmMemoryEntry,
  WasmFingerprintConfig,
  WasmReadabilityResult as WasmReadabilityResultType,
  WasmReadabilityConfig as WasmReadabilityConfigType,
  WasmPageResult as WasmPageResultType,
  WasmLayoutElement as WasmLayoutElementType,
  WasmElement as WasmElementType,
} from './pkg/bundler/thalora'

// ============================================================================
// Type Exports
// ============================================================================

export interface ScrapedData {
  url: string
  title: string
  content: string
  html: string
}

export interface Link {
  url: string
  text: string
}

export interface Image {
  url: string
  alt: string
}

export interface BrowserConfig {
  userAgent?: string
  viewportWidth?: number
  viewportHeight?: number
  javascriptEnabled?: boolean
  stealthMode?: boolean
}

export interface MemoryEntry {
  id: string
  entryType: string
  title: string
  content: string
  tags: string[]
  createdAt: string
  updatedAt: string
}

export interface MemoryStats {
  total: number
  research: number
  bookmark: number
  note: number
}

export interface FingerprintConfig {
  userAgent: string
  platform: string
  language: string
  screenWidth: number
  screenHeight: number
  colorDepth: number
  timezone: string
  webglVendor: string
  webglRenderer: string
}

// ============================================================================
// Readability Types
// ============================================================================

export interface ReadabilityResult {
  content: string
  format: string
  title: string
  author?: string
  publishedDate?: string
  mainImage?: string
  wordCount: number
  readingTimeMinutes: number
  readabilityScore: number
  success: boolean
  error?: string
}

export interface ReadabilityConfig {
  minContentScore: number
  maxLinkDensity: number
  minParagraphCount: number
  includeImages: boolean
  includeMetadata: boolean
  outputFormat: 'markdown' | 'text' | 'structured'
}

// ============================================================================
// CSS Processor Types
// ============================================================================

export interface ComputedStyles {
  display?: string
  position?: string
  width?: string
  height?: string
  flexDirection?: string
  justifyContent?: string
  alignItems?: string
  gap?: string
  margin?: BoxModel
  padding?: BoxModel
  color?: string
  backgroundColor?: string
  fontSize?: string
  fontWeight?: string
  fontFamily?: string
  lineHeight?: string
  textAlign?: string
  border?: string
  borderRadius?: string
  overflow?: string
  zIndex?: number
  opacity?: number
}

export interface BoxModel {
  top: number
  right: number
  bottom: number
  left: number
}

export interface ParsedRule {
  selector: string
  properties: Record<string, string>
  specificity: number
}

// ============================================================================
// Layout Engine Types
// ============================================================================

export interface LayoutElement {
  id: string
  tag: string
  styles: Record<string, string | undefined>
  children: LayoutElement[]
}

export interface ElementLayout {
  id: string
  x: number
  y: number
  width: number
  height: number
  contentBox: ContentBox
  children: ElementLayout[]
}

export interface ContentBox {
  x: number
  y: number
  width: number
  height: number
}

export interface LayoutResult {
  root: ElementLayout
  viewportWidth: number
  viewportHeight: number
}

// ============================================================================
// Page Processor Types
// ============================================================================

export interface PageResult {
  url: string
  title?: string
  readableContent: string
  textContent: string
  links: Link[]
  images: Image[]
  metadata: Record<string, string>
  isReadable: boolean
  readabilityScore: number
  wordCount: number
  processingTimeMs: number
}

// ============================================================================
// DOM Types
// ============================================================================

export interface DOMElement {
  tag: string
  id?: string
  classes: string[]
  attributes: Record<string, string>
  textContent: string
  innerHTML: string
}

export interface FormField {
  type: string
  name: string
  id: string
  value: string
}

export interface FormData {
  action: string
  method: string
  id: string
  fields: FormField[]
}

export interface Heading {
  level: string
  text: string
  id?: string
}

// ============================================================================
// Thalora Browser Class
// ============================================================================

/**
 * Main Thalora Browser instance
 *
 * Provides headless browser functionality that runs entirely in the browser.
 */
export class ThaloraBrowser {
  private wasmModule: any = null
  private wasmBrowser: WasmThaloraBrowser | null = null
  private _storage: ThaloraStorage | null = null
  private _aiMemory: ThaloraAIMemory | null = null
  private _fingerprint: ThaloraFingerprint | null = null
  private _cssProcessor: ThaloraCssProcessor | null = null
  private _layoutEngine: ThaloraLayoutEngine | null = null
  private _jsEngine: ThaloraJsEngine | null = null
  private _pageProcessor: ThaloraPageProcessor | null = null

  /**
   * Initialize the browser
   */
  async initialize(config?: BrowserConfig): Promise<void> {
    // Load WASM module
    this.wasmModule = await this.loadWasmModule()

    // Create browser instance
    if (config) {
      const wasmConfig = {
        user_agent: config.userAgent,
        viewport_width: config.viewportWidth,
        viewport_height: config.viewportHeight,
        javascript_enabled: config.javascriptEnabled ?? true,
        stealth_mode: config.stealthMode ?? false,
      }
      this.wasmBrowser = this.wasmModule.ThaloraBrowser.with_config(wasmConfig)
    } else {
      this.wasmBrowser = new this.wasmModule.ThaloraBrowser()
    }

    console.log('Thalora Browser initialized')
  }

  /**
   * Load the WASM module
   */
  private async loadWasmModule(): Promise<any> {
    try {
      const wasmModule = await import('./pkg/bundler/thalora')
      return wasmModule
    } catch (error) {
      console.error('Failed to load WASM module:', error)
      throw new Error('Failed to initialize Thalora WASM module')
    }
  }

  /**
   * Navigate to a URL and fetch the page
   *
   * Note: This delegates to the browser's fetch API for actual networking
   */
  async navigate(url: string): Promise<ScrapedData> {
    if (!this.wasmBrowser) {
      throw new Error('Browser not initialized. Call initialize() first.')
    }

    // Use browser fetch API for actual network request
    const response = await fetch(url)
    const html = await response.text()

    // Parse with WASM DOM parser
    const dom = new this.wasmModule.WasmDOM(html)

    return {
      url,
      title: dom.get_title() || '',
      content: dom.get_text(),
      html,
    }
  }

  /**
   * Execute JavaScript code in a sandboxed Boa engine context
   */
  executeJS(code: string): string {
    if (!this.wasmBrowser) {
      throw new Error('Browser not initialized. Call initialize() first.')
    }
    return this.wasmBrowser.execute_js(code)
  }

  /**
   * Get current configuration
   */
  getConfig(): BrowserConfig {
    if (!this.wasmBrowser) {
      throw new Error('Browser not initialized. Call initialize() first.')
    }
    const config = this.wasmBrowser.get_config()
    return {
      userAgent: config.user_agent,
      viewportWidth: config.viewport_width,
      viewportHeight: config.viewport_height,
      javascriptEnabled: config.javascript_enabled,
      stealthMode: config.stealth_mode,
    }
  }

  /**
   * Set user agent string
   */
  setUserAgent(userAgent: string): void {
    if (!this.wasmBrowser) {
      throw new Error('Browser not initialized. Call initialize() first.')
    }
    this.wasmBrowser.set_user_agent(userAgent)
  }

  /**
   * Set viewport dimensions
   */
  setViewport(width: number, height: number): void {
    if (!this.wasmBrowser) {
      throw new Error('Browser not initialized. Call initialize() first.')
    }
    this.wasmBrowser.set_viewport(width, height)
  }

  /**
   * Enable or disable JavaScript execution
   */
  setJavaScriptEnabled(enabled: boolean): void {
    if (!this.wasmBrowser) {
      throw new Error('Browser not initialized. Call initialize() first.')
    }
    this.wasmBrowser.set_javascript_enabled(enabled)
  }

  /**
   * Enable or disable stealth mode
   */
  setStealthMode(enabled: boolean): void {
    if (!this.wasmBrowser) {
      throw new Error('Browser not initialized. Call initialize() first.')
    }
    this.wasmBrowser.set_stealth_mode(enabled)
  }

  /**
   * Get storage manager
   */
  get storage(): ThaloraStorage {
    if (!this._storage) {
      if (!this.wasmModule) {
        throw new Error('Browser not initialized. Call initialize() first.')
      }
      this._storage = new ThaloraStorage(this.wasmModule, 'default')
    }
    return this._storage
  }

  /**
   * Get AI memory manager
   */
  get aiMemory(): ThaloraAIMemory {
    if (!this._aiMemory) {
      if (!this.wasmModule) {
        throw new Error('Browser not initialized. Call initialize() first.')
      }
      this._aiMemory = new ThaloraAIMemory(this.wasmModule)
    }
    return this._aiMemory
  }

  /**
   * Get fingerprint manager
   */
  get fingerprint(): ThaloraFingerprint {
    if (!this._fingerprint) {
      if (!this.wasmModule) {
        throw new Error('Browser not initialized. Call initialize() first.')
      }
      this._fingerprint = new ThaloraFingerprint(this.wasmModule)
    }
    return this._fingerprint
  }

  /**
   * Get CSS processor (lightningcss)
   */
  get cssProcessor(): ThaloraCssProcessor {
    if (!this._cssProcessor) {
      if (!this.wasmModule) {
        throw new Error('Browser not initialized. Call initialize() first.')
      }
      this._cssProcessor = new ThaloraCssProcessor(this.wasmModule)
    }
    return this._cssProcessor
  }

  /**
   * Get layout engine (taffy)
   */
  get layoutEngine(): ThaloraLayoutEngine {
    if (!this._layoutEngine) {
      if (!this.wasmModule) {
        throw new Error('Browser not initialized. Call initialize() first.')
      }
      this._layoutEngine = new ThaloraLayoutEngine(this.wasmModule)
    }
    return this._layoutEngine
  }

  /**
   * Get JavaScript engine (Boa)
   */
  get jsEngine(): ThaloraJsEngine {
    if (!this._jsEngine) {
      if (!this.wasmModule) {
        throw new Error('Browser not initialized. Call initialize() first.')
      }
      this._jsEngine = new ThaloraJsEngine(this.wasmModule)
    }
    return this._jsEngine
  }

  /**
   * Get page processor (unified pipeline)
   */
  get pageProcessor(): ThaloraPageProcessor {
    if (!this._pageProcessor) {
      if (!this.wasmModule) {
        throw new Error('Browser not initialized. Call initialize() first.')
      }
      this._pageProcessor = new ThaloraPageProcessor(this.wasmModule)
    }
    return this._pageProcessor
  }

  /**
   * Create a new DOM parser for HTML content
   */
  createDOM(html: string): ThaloraDOM {
    if (!this.wasmModule) {
      throw new Error('Browser not initialized. Call initialize() first.')
    }
    return new ThaloraDOM(this.wasmModule, html)
  }

  /**
   * Create a new readability extractor
   */
  createReadability(config?: ReadabilityConfig): ThaloraReadability {
    if (!this.wasmModule) {
      throw new Error('Browser not initialized. Call initialize() first.')
    }
    return new ThaloraReadability(this.wasmModule, config)
  }

  /**
   * Get library version
   */
  static getVersion(): string {
    return '0.1.0' // Will be updated from WASM after init
  }

  /**
   * Check if running in WASM mode
   */
  static isWasm(): boolean {
    return true
  }
}

// ============================================================================
// Storage Class
// ============================================================================

/**
 * Browser storage manager
 */
export class ThaloraStorage {
  private wasmStorage: WasmStorageType

  constructor(wasmModule: any, namespace: string) {
    this.wasmStorage = new wasmModule.WasmStorage(namespace)
  }

  get(key: string): string | null {
    return this.wasmStorage.get(key) ?? null
  }

  set(key: string, value: string): void {
    this.wasmStorage.set(key, value)
  }

  remove(key: string): boolean {
    return this.wasmStorage.remove(key)
  }

  clear(): void {
    this.wasmStorage.clear()
  }

  keys(): string[] {
    return this.wasmStorage.keys()
  }

  get length(): number {
    return this.wasmStorage.length()
  }

  exportJSON(): string {
    return this.wasmStorage.export_json()
  }

  importJSON(json: string): void {
    this.wasmStorage.import_json(json)
  }
}

// ============================================================================
// AI Memory Class
// ============================================================================

/**
 * AI Memory manager for persistent storage of research, bookmarks, and notes
 */
export class ThaloraAIMemory {
  private wasmMemory: WasmAIMemoryType

  constructor(wasmModule: any) {
    this.wasmMemory = new wasmModule.WasmAIMemory()
  }

  /**
   * Add a research entry
   */
  addResearch(title: string, content: string, tags: string[] = []): string {
    return this.wasmMemory.add_research(title, content, tags)
  }

  /**
   * Add a bookmark
   */
  addBookmark(url: string, title: string, description: string = ''): string {
    return this.wasmMemory.add_bookmark(url, title, description)
  }

  /**
   * Add a note
   */
  addNote(
    title: string,
    content: string,
    priority: 'low' | 'medium' | 'high' = 'medium'
  ): string {
    return this.wasmMemory.add_note(title, content, priority)
  }

  /**
   * Get an entry by ID
   */
  get(id: string): MemoryEntry | null {
    const json = this.wasmMemory.get(id)
    if (!json) return null
    const entry = JSON.parse(json)
    return this.convertEntry(entry)
  }

  /**
   * Delete an entry
   */
  delete(id: string): boolean {
    return this.wasmMemory.delete(id)
  }

  /**
   * Search entries
   */
  search(query: string): MemoryEntry[] {
    const results = this.wasmMemory.search(query)
    return results.map((e: WasmMemoryEntry) => this.convertEntry(e))
  }

  /**
   * List all entries
   */
  listAll(): MemoryEntry[] {
    const results = this.wasmMemory.list_all()
    return results.map((e: WasmMemoryEntry) => this.convertEntry(e))
  }

  /**
   * Get statistics
   */
  getStats(): MemoryStats {
    return this.wasmMemory.get_stats()
  }

  /**
   * Export all memory as JSON
   */
  exportJSON(): string {
    return this.wasmMemory.export_json()
  }

  /**
   * Import memory from JSON
   */
  importJSON(json: string): void {
    this.wasmMemory.import_json(json)
  }

  private convertEntry(entry: WasmMemoryEntry): MemoryEntry {
    return {
      id: entry.id,
      entryType: entry.entry_type,
      title: entry.title,
      content: entry.content,
      tags: entry.tags,
      createdAt: entry.created_at,
      updatedAt: entry.updated_at,
    }
  }
}

// ============================================================================
// Fingerprint Class
// ============================================================================

/**
 * Browser fingerprint manager for stealth browsing
 */
export class ThaloraFingerprint {
  private wasmFingerprint: WasmFingerprintType

  constructor(wasmModule: any) {
    this.wasmFingerprint = new wasmModule.WasmFingerprint()
  }

  /**
   * Randomize all fingerprint values
   */
  randomize(): void {
    this.wasmFingerprint.randomize()
  }

  /**
   * Get current configuration
   */
  getConfig(): FingerprintConfig {
    const config = this.wasmFingerprint.get_config()
    return {
      userAgent: config.user_agent,
      platform: config.platform,
      language: config.language,
      screenWidth: config.screen_width,
      screenHeight: config.screen_height,
      colorDepth: config.color_depth,
      timezone: config.timezone,
      webglVendor: config.webgl_vendor,
      webglRenderer: config.webgl_renderer,
    }
  }

  /**
   * Set user agent
   */
  setUserAgent(userAgent: string): void {
    this.wasmFingerprint.set_user_agent(userAgent)
  }

  /**
   * Set platform
   */
  setPlatform(platform: string): void {
    this.wasmFingerprint.set_platform(platform)
  }

  /**
   * Set screen resolution
   */
  setResolution(width: number, height: number): void {
    this.wasmFingerprint.set_resolution(width, height)
  }

  /**
   * Set timezone
   */
  setTimezone(timezone: string): void {
    this.wasmFingerprint.set_timezone(timezone)
  }

  /**
   * Get JavaScript injection script for fingerprint spoofing
   */
  getInjectionScript(): string {
    return this.wasmFingerprint.get_injection_script()
  }
}

// ============================================================================
// DOM Parser Class
// ============================================================================

/**
 * DOM parser for extracting content from HTML using html5ever
 */
export class ThaloraDOM {
  private wasmDOM: WasmDOMType

  constructor(wasmModule: any, html: string) {
    this.wasmDOM = new wasmModule.WasmDOM(html)
  }

  /**
   * Get raw HTML
   */
  getHTML(): string {
    return this.wasmDOM.get_html()
  }

  /**
   * Get serialized HTML from the parsed document
   */
  getSerializedHTML(): string {
    return this.wasmDOM.get_serialized_html()
  }

  /**
   * Get text content (tags stripped)
   */
  getText(): string {
    return this.wasmDOM.get_text()
  }

  /**
   * Get page title
   */
  getTitle(): string | null {
    return this.wasmDOM.get_title() ?? null
  }

  /**
   * Get meta description
   */
  getMetaDescription(): string | null {
    return this.wasmDOM.get_meta_description() ?? null
  }

  /**
   * Get meta keywords
   */
  getMetaKeywords(): string[] {
    return this.wasmDOM.get_meta_keywords()
  }

  /**
   * Get Open Graph metadata
   */
  getOgMetadata(): Record<string, string> {
    return this.wasmDOM.get_og_metadata()
  }

  /**
   * Query a single element by CSS selector
   */
  querySelector(selector: string): DOMElement | null {
    return this.wasmDOM.query_selector(selector)
  }

  /**
   * Query all elements matching a CSS selector
   */
  querySelectorAll(selector: string): DOMElement[] {
    return this.wasmDOM.query_selector_all(selector)
  }

  /**
   * Extract all links
   */
  getLinks(): Link[] {
    const links = this.wasmDOM.get_links()
    return links.map((l: WasmLink) => ({
      url: l.url,
      text: l.text,
    }))
  }

  /**
   * Extract all images
   */
  getImages(): Image[] {
    const images = this.wasmDOM.get_images()
    return images.map((i: WasmImage) => ({
      url: i.url,
      alt: i.alt,
    }))
  }

  /**
   * Extract all forms
   */
  getForms(): FormData[] {
    return this.wasmDOM.get_forms()
  }

  /**
   * Extract all headings (h1-h6)
   */
  getHeadings(): Heading[] {
    return this.wasmDOM.get_headings()
  }

  /**
   * Count elements matching a tag name
   */
  countElements(tag: string): number {
    return this.wasmDOM.count_elements(tag)
  }

  /**
   * Check if an element exists matching the selector
   */
  hasElement(selector: string): boolean {
    return this.wasmDOM.has_element(selector)
  }

  /**
   * Get attribute value for first matching element
   */
  getAttribute(selector: string, attribute: string): string | null {
    return this.wasmDOM.get_attribute(selector, attribute) ?? null
  }

  /**
   * Get all script sources
   */
  getScriptSources(): string[] {
    return this.wasmDOM.get_script_sources()
  }

  /**
   * Get all stylesheet links
   */
  getStylesheetLinks(): string[] {
    return this.wasmDOM.get_stylesheet_links()
  }

  /**
   * Get inline styles
   */
  getInlineStyles(): string[] {
    return this.wasmDOM.get_inline_styles()
  }
}

// ============================================================================
// Readability Class
// ============================================================================

/**
 * Content extractor for readable articles (similar to Chrome's reading mode)
 */
export class ThaloraReadability {
  private wasmReadability: WasmReadabilityType

  constructor(wasmModule: any, config?: ReadabilityConfig) {
    if (config) {
      const wasmConfig = {
        min_content_score: config.minContentScore,
        max_link_density: config.maxLinkDensity,
        min_paragraph_count: config.minParagraphCount,
        include_images: config.includeImages,
        include_metadata: config.includeMetadata,
        output_format: config.outputFormat,
      }
      this.wasmReadability = wasmModule.WasmReadability.with_config(wasmConfig)
    } else {
      this.wasmReadability = new wasmModule.WasmReadability()
    }
  }

  /**
   * Extract readable content from HTML
   */
  extract(html: string, url: string): ReadabilityResult {
    const result = this.wasmReadability.extract(html, url)
    return {
      content: result.content,
      format: result.format,
      title: result.title,
      author: result.author ?? undefined,
      publishedDate: result.published_date ?? undefined,
      mainImage: result.main_image ?? undefined,
      wordCount: result.word_count,
      readingTimeMinutes: result.reading_time_minutes,
      readabilityScore: result.readability_score,
      success: result.success,
      error: result.error ?? undefined,
    }
  }

  /**
   * Quick extraction with default settings
   */
  extractQuick(html: string, url: string): ReadabilityResult {
    return this.extract(html, url)
  }

  /**
   * Extract only text content without formatting
   */
  extractTextOnly(html: string, url: string): string {
    return this.wasmReadability.extract_text_only(html, url)
  }

  /**
   * Check if a page is likely to have readable content
   */
  isReadable(html: string, url: string): boolean {
    return this.wasmReadability.is_readable(html, url)
  }

  /**
   * Get current configuration
   */
  getConfig(): ReadabilityConfig {
    const config = this.wasmReadability.get_config()
    return {
      minContentScore: config.min_content_score,
      maxLinkDensity: config.max_link_density,
      minParagraphCount: config.min_paragraph_count,
      includeImages: config.include_images,
      includeMetadata: config.include_metadata,
      outputFormat: config.output_format,
    }
  }

  /**
   * Update configuration
   */
  setConfig(config: ReadabilityConfig): void {
    const wasmConfig = {
      min_content_score: config.minContentScore,
      max_link_density: config.maxLinkDensity,
      min_paragraph_count: config.minParagraphCount,
      include_images: config.includeImages,
      include_metadata: config.includeMetadata,
      output_format: config.outputFormat,
    }
    this.wasmReadability.set_config(wasmConfig)
  }

  /**
   * Set output format
   */
  setOutputFormat(format: 'markdown' | 'text' | 'structured'): void {
    this.wasmReadability.set_output_format(format)
  }
}

// ============================================================================
// CSS Processor Class
// ============================================================================

/**
 * CSS parser and style computation using lightningcss
 */
export class ThaloraCssProcessor {
  private wasmProcessor: WasmCssProcessorType

  constructor(wasmModule: any) {
    this.wasmProcessor = new wasmModule.WasmCssProcessor()
  }

  /**
   * Parse CSS and add its rules to the processor
   */
  parse(css: string): void {
    this.wasmProcessor.parse(css)
  }

  /**
   * Compute styles for a given selector
   */
  computeStyle(selector: string): ComputedStyles {
    return this.wasmProcessor.compute_style(selector)
  }

  /**
   * Get a specific CSS property value
   */
  getProperty(selector: string, property: string): string | null {
    return this.wasmProcessor.get_property(selector, property) ?? null
  }

  /**
   * Minify CSS
   */
  minify(css: string): string {
    return this.wasmProcessor.minify(css)
  }

  /**
   * Process CSS (returns processed CSS)
   */
  process(css: string): string {
    return this.wasmProcessor.process(css)
  }

  /**
   * Get all parsed rules
   */
  getRules(): ParsedRule[] {
    return this.wasmProcessor.get_rules()
  }

  /**
   * Clear all parsed rules
   */
  clear(): void {
    this.wasmProcessor.clear()
  }
}

// ============================================================================
// Layout Engine Class
// ============================================================================

/**
 * CSS-compliant layout engine using taffy
 */
export class ThaloraLayoutEngine {
  private wasmEngine: WasmLayoutEngineType

  constructor(wasmModule: any, viewportWidth?: number, viewportHeight?: number) {
    if (viewportWidth !== undefined && viewportHeight !== undefined) {
      this.wasmEngine = wasmModule.WasmLayoutEngine.with_viewport(
        viewportWidth,
        viewportHeight
      )
    } else {
      this.wasmEngine = new wasmModule.WasmLayoutEngine()
    }
  }

  /**
   * Set viewport dimensions
   */
  setViewport(width: number, height: number): void {
    this.wasmEngine.set_viewport(width, height)
  }

  /**
   * Calculate layout for an element tree
   */
  calculateLayout(root: LayoutElement): LayoutResult {
    const wasmRoot = this.convertToWasmElement(root)
    return this.wasmEngine.calculate_layout(wasmRoot)
  }

  private convertToWasmElement(element: LayoutElement): any {
    return {
      id: element.id,
      tag: element.tag,
      styles: element.styles,
      children: element.children.map((c) => this.convertToWasmElement(c)),
    }
  }
}

// ============================================================================
// JavaScript Engine Class
// ============================================================================

/**
 * Sandboxed JavaScript execution engine using Boa
 */
export class ThaloraJsEngine {
  private wasmEngine: WasmJsEngineType

  constructor(wasmModule: any) {
    this.wasmEngine = new wasmModule.WasmJsEngine()
  }

  /**
   * Execute JavaScript code and return the result
   */
  async execute(code: string): Promise<any> {
    return await this.wasmEngine.execute(code)
  }

  /**
   * Execute JavaScript code synchronously
   */
  executeSync(code: string): any {
    return this.wasmEngine.execute_sync(code)
  }

  /**
   * Set a global variable in the JavaScript context
   */
  setGlobal(name: string, value: any): void {
    this.wasmEngine.set_global(name, value)
  }

  /**
   * Get a global variable from the JavaScript context
   */
  getGlobal(name: string): any {
    return this.wasmEngine.get_global(name)
  }

  /**
   * Run pending microtasks (promises, etc.)
   */
  runJobs(): void {
    this.wasmEngine.run_jobs()
  }

  /**
   * Get engine version information
   */
  version(): string {
    return this.wasmEngine.version()
  }
}

// ============================================================================
// Page Processor Class
// ============================================================================

/**
 * Unified page processing pipeline combining DOM, CSS, and readability
 */
export class ThaloraPageProcessor {
  private wasmProcessor: WasmPageProcessorType

  constructor(wasmModule: any) {
    this.wasmProcessor = new wasmModule.WasmPageProcessor()
  }

  /**
   * Process a page and extract all relevant data
   */
  process(html: string, url: string): PageResult {
    const result = this.wasmProcessor.process(html, url)
    return {
      url: result.url,
      title: result.title ?? undefined,
      readableContent: result.readable_content,
      textContent: result.text_content,
      links: result.links.map((l: WasmLink) => ({
        url: l.url,
        text: l.text,
      })),
      images: result.images.map((i: WasmImage) => ({
        url: i.url,
        alt: i.alt,
      })),
      metadata: result.metadata,
      isReadable: result.is_readable,
      readabilityScore: result.readability_score,
      wordCount: result.word_count,
      processingTimeMs: result.processing_time_ms,
    }
  }

  /**
   * Quick process - just extract text and links
   */
  processQuick(html: string, url: string): PageResult {
    const result = this.wasmProcessor.process_quick(html, url)
    return {
      url: result.url,
      title: result.title ?? undefined,
      readableContent: result.readable_content,
      textContent: result.text_content,
      links: result.links.map((l: WasmLink) => ({
        url: l.url,
        text: l.text,
      })),
      images: result.images.map((i: WasmImage) => ({
        url: i.url,
        alt: i.alt,
      })),
      metadata: result.metadata,
      isReadable: result.is_readable,
      readabilityScore: result.readability_score,
      wordCount: result.word_count,
      processingTimeMs: result.processing_time_ms,
    }
  }

  /**
   * Extract only readable content
   */
  extractReadable(html: string, url: string): ReadabilityResult {
    const result = this.wasmProcessor.extract_readable(html, url)
    return {
      content: result.content,
      format: result.format,
      title: result.title,
      author: result.author ?? undefined,
      publishedDate: result.published_date ?? undefined,
      mainImage: result.main_image ?? undefined,
      wordCount: result.word_count,
      readingTimeMinutes: result.reading_time_minutes,
      readabilityScore: result.readability_score,
      success: result.success,
      error: result.error ?? undefined,
    }
  }

  /**
   * Check if a page is likely readable
   */
  isReadable(html: string, url: string): boolean {
    return this.wasmProcessor.is_readable(html, url)
  }
}

// ============================================================================
// Factory Function
// ============================================================================

/**
 * Create and initialize a ThaloraBrowser instance
 */
export async function createBrowser(
  config?: BrowserConfig
): Promise<ThaloraBrowser> {
  const browser = new ThaloraBrowser()
  await browser.initialize(config)
  return browser
}

// ============================================================================
// Utility Functions
// ============================================================================

/**
 * Format bytes to human-readable string
 */
export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(2)} KB`
  if (bytes < 1024 * 1024 * 1024)
    return `${(bytes / (1024 * 1024)).toFixed(2)} MB`
  return `${(bytes / (1024 * 1024 * 1024)).toFixed(2)} GB`
}

// Default export
export default ThaloraBrowser
