/**
 * TypeScript wrapper for Thalora Web Browser WASM module
 *
 * Provides a high-level, type-safe API for browser automation,
 * AI memory management, and fingerprint spoofing.
 */

// Import WASM module types (generated by wasm-pack)
import type {
  ThaloraBrowser as WasmThaloraBrowser,
  WasmStorage as WasmStorageType,
  WasmAIMemory as WasmAIMemoryType,
  WasmFingerprint as WasmFingerprintType,
  WasmDOM as WasmDOMType,
  WasmScrapedData,
  WasmLink,
  WasmImage,
  WasmMemoryEntry,
  WasmFingerprintConfig,
} from './pkg/bundler/thalora'

// ============================================================================
// Type Exports
// ============================================================================

export interface ScrapedData {
  url: string
  title: string
  content: string
  html: string
}

export interface Link {
  url: string
  text: string
}

export interface Image {
  url: string
  alt: string
}

export interface BrowserConfig {
  userAgent?: string
  viewportWidth?: number
  viewportHeight?: number
  javascriptEnabled?: boolean
  stealthMode?: boolean
}

export interface MemoryEntry {
  id: string
  entryType: string
  title: string
  content: string
  tags: string[]
  createdAt: string
  updatedAt: string
}

export interface MemoryStats {
  total: number
  research: number
  bookmark: number
  note: number
}

export interface FingerprintConfig {
  userAgent: string
  platform: string
  language: string
  screenWidth: number
  screenHeight: number
  colorDepth: number
  timezone: string
  webglVendor: string
  webglRenderer: string
}

// ============================================================================
// Thalora Browser Class
// ============================================================================

/**
 * Main Thalora Browser instance
 *
 * Provides headless browser functionality that runs entirely in the browser.
 */
export class ThaloraBrowser {
  private wasmModule: any = null
  private wasmBrowser: WasmThaloraBrowser | null = null
  private _storage: ThaloraStorage | null = null
  private _aiMemory: ThaloraAIMemory | null = null
  private _fingerprint: ThaloraFingerprint | null = null

  /**
   * Initialize the browser
   */
  async initialize(config?: BrowserConfig): Promise<void> {
    // Load WASM module
    this.wasmModule = await this.loadWasmModule()

    // Create browser instance
    if (config) {
      const wasmConfig = {
        user_agent: config.userAgent,
        viewport_width: config.viewportWidth,
        viewport_height: config.viewportHeight,
        javascript_enabled: config.javascriptEnabled ?? true,
        stealth_mode: config.stealthMode ?? false,
      }
      this.wasmBrowser = this.wasmModule.ThaloraBrowser.with_config(wasmConfig)
    } else {
      this.wasmBrowser = new this.wasmModule.ThaloraBrowser()
    }

    console.log('Thalora Browser initialized')
  }

  /**
   * Load the WASM module
   */
  private async loadWasmModule(): Promise<any> {
    try {
      const wasmModule = await import('./pkg/bundler/thalora')
      return wasmModule
    } catch (error) {
      console.error('Failed to load WASM module:', error)
      throw new Error('Failed to initialize Thalora WASM module')
    }
  }

  /**
   * Navigate to a URL and fetch the page
   *
   * Note: This delegates to the browser's fetch API for actual networking
   */
  async navigate(url: string): Promise<ScrapedData> {
    if (!this.wasmBrowser) {
      throw new Error('Browser not initialized. Call initialize() first.')
    }

    // Use browser fetch API for actual network request
    const response = await fetch(url)
    const html = await response.text()

    // Parse with WASM DOM parser
    const dom = new this.wasmModule.WasmDOM(html)

    return {
      url,
      title: dom.get_title() || '',
      content: dom.get_text(),
      html,
    }
  }

  /**
   * Execute JavaScript code in a sandboxed Boa engine context
   */
  executeJS(code: string): string {
    if (!this.wasmBrowser) {
      throw new Error('Browser not initialized. Call initialize() first.')
    }
    return this.wasmBrowser.execute_js(code)
  }

  /**
   * Get current configuration
   */
  getConfig(): BrowserConfig {
    if (!this.wasmBrowser) {
      throw new Error('Browser not initialized. Call initialize() first.')
    }
    const config = this.wasmBrowser.get_config()
    return {
      userAgent: config.user_agent,
      viewportWidth: config.viewport_width,
      viewportHeight: config.viewport_height,
      javascriptEnabled: config.javascript_enabled,
      stealthMode: config.stealth_mode,
    }
  }

  /**
   * Set user agent string
   */
  setUserAgent(userAgent: string): void {
    if (!this.wasmBrowser) {
      throw new Error('Browser not initialized. Call initialize() first.')
    }
    this.wasmBrowser.set_user_agent(userAgent)
  }

  /**
   * Set viewport dimensions
   */
  setViewport(width: number, height: number): void {
    if (!this.wasmBrowser) {
      throw new Error('Browser not initialized. Call initialize() first.')
    }
    this.wasmBrowser.set_viewport(width, height)
  }

  /**
   * Enable or disable JavaScript execution
   */
  setJavaScriptEnabled(enabled: boolean): void {
    if (!this.wasmBrowser) {
      throw new Error('Browser not initialized. Call initialize() first.')
    }
    this.wasmBrowser.set_javascript_enabled(enabled)
  }

  /**
   * Enable or disable stealth mode
   */
  setStealthMode(enabled: boolean): void {
    if (!this.wasmBrowser) {
      throw new Error('Browser not initialized. Call initialize() first.')
    }
    this.wasmBrowser.set_stealth_mode(enabled)
  }

  /**
   * Get storage manager
   */
  get storage(): ThaloraStorage {
    if (!this._storage) {
      if (!this.wasmModule) {
        throw new Error('Browser not initialized. Call initialize() first.')
      }
      this._storage = new ThaloraStorage(this.wasmModule, 'default')
    }
    return this._storage
  }

  /**
   * Get AI memory manager
   */
  get aiMemory(): ThaloraAIMemory {
    if (!this._aiMemory) {
      if (!this.wasmModule) {
        throw new Error('Browser not initialized. Call initialize() first.')
      }
      this._aiMemory = new ThaloraAIMemory(this.wasmModule)
    }
    return this._aiMemory
  }

  /**
   * Get fingerprint manager
   */
  get fingerprint(): ThaloraFingerprint {
    if (!this._fingerprint) {
      if (!this.wasmModule) {
        throw new Error('Browser not initialized. Call initialize() first.')
      }
      this._fingerprint = new ThaloraFingerprint(this.wasmModule)
    }
    return this._fingerprint
  }

  /**
   * Get library version
   */
  static getVersion(): string {
    return '0.1.0' // Will be updated from WASM after init
  }

  /**
   * Check if running in WASM mode
   */
  static isWasm(): boolean {
    return true
  }
}

// ============================================================================
// Storage Class
// ============================================================================

/**
 * Browser storage manager
 */
export class ThaloraStorage {
  private wasmStorage: WasmStorageType

  constructor(wasmModule: any, namespace: string) {
    this.wasmStorage = new wasmModule.WasmStorage(namespace)
  }

  get(key: string): string | null {
    return this.wasmStorage.get(key) ?? null
  }

  set(key: string, value: string): void {
    this.wasmStorage.set(key, value)
  }

  remove(key: string): boolean {
    return this.wasmStorage.remove(key)
  }

  clear(): void {
    this.wasmStorage.clear()
  }

  keys(): string[] {
    return this.wasmStorage.keys()
  }

  get length(): number {
    return this.wasmStorage.length()
  }

  exportJSON(): string {
    return this.wasmStorage.export_json()
  }

  importJSON(json: string): void {
    this.wasmStorage.import_json(json)
  }
}

// ============================================================================
// AI Memory Class
// ============================================================================

/**
 * AI Memory manager for persistent storage of research, bookmarks, and notes
 */
export class ThaloraAIMemory {
  private wasmMemory: WasmAIMemoryType

  constructor(wasmModule: any) {
    this.wasmMemory = new wasmModule.WasmAIMemory()
  }

  /**
   * Add a research entry
   */
  addResearch(title: string, content: string, tags: string[] = []): string {
    return this.wasmMemory.add_research(title, content, tags)
  }

  /**
   * Add a bookmark
   */
  addBookmark(url: string, title: string, description: string = ''): string {
    return this.wasmMemory.add_bookmark(url, title, description)
  }

  /**
   * Add a note
   */
  addNote(
    title: string,
    content: string,
    priority: 'low' | 'medium' | 'high' = 'medium'
  ): string {
    return this.wasmMemory.add_note(title, content, priority)
  }

  /**
   * Get an entry by ID
   */
  get(id: string): MemoryEntry | null {
    const json = this.wasmMemory.get(id)
    if (!json) return null
    const entry = JSON.parse(json)
    return this.convertEntry(entry)
  }

  /**
   * Delete an entry
   */
  delete(id: string): boolean {
    return this.wasmMemory.delete(id)
  }

  /**
   * Search entries
   */
  search(query: string): MemoryEntry[] {
    const results = this.wasmMemory.search(query)
    return results.map((e: WasmMemoryEntry) => this.convertEntry(e))
  }

  /**
   * List all entries
   */
  listAll(): MemoryEntry[] {
    const results = this.wasmMemory.list_all()
    return results.map((e: WasmMemoryEntry) => this.convertEntry(e))
  }

  /**
   * Get statistics
   */
  getStats(): MemoryStats {
    return this.wasmMemory.get_stats()
  }

  /**
   * Export all memory as JSON
   */
  exportJSON(): string {
    return this.wasmMemory.export_json()
  }

  /**
   * Import memory from JSON
   */
  importJSON(json: string): void {
    this.wasmMemory.import_json(json)
  }

  private convertEntry(entry: WasmMemoryEntry): MemoryEntry {
    return {
      id: entry.id,
      entryType: entry.entry_type,
      title: entry.title,
      content: entry.content,
      tags: entry.tags,
      createdAt: entry.created_at,
      updatedAt: entry.updated_at,
    }
  }
}

// ============================================================================
// Fingerprint Class
// ============================================================================

/**
 * Browser fingerprint manager for stealth browsing
 */
export class ThaloraFingerprint {
  private wasmFingerprint: WasmFingerprintType

  constructor(wasmModule: any) {
    this.wasmFingerprint = new wasmModule.WasmFingerprint()
  }

  /**
   * Randomize all fingerprint values
   */
  randomize(): void {
    this.wasmFingerprint.randomize()
  }

  /**
   * Get current configuration
   */
  getConfig(): FingerprintConfig {
    const config = this.wasmFingerprint.get_config()
    return {
      userAgent: config.user_agent,
      platform: config.platform,
      language: config.language,
      screenWidth: config.screen_width,
      screenHeight: config.screen_height,
      colorDepth: config.color_depth,
      timezone: config.timezone,
      webglVendor: config.webgl_vendor,
      webglRenderer: config.webgl_renderer,
    }
  }

  /**
   * Set user agent
   */
  setUserAgent(userAgent: string): void {
    this.wasmFingerprint.set_user_agent(userAgent)
  }

  /**
   * Set platform
   */
  setPlatform(platform: string): void {
    this.wasmFingerprint.set_platform(platform)
  }

  /**
   * Set screen resolution
   */
  setResolution(width: number, height: number): void {
    this.wasmFingerprint.set_resolution(width, height)
  }

  /**
   * Set timezone
   */
  setTimezone(timezone: string): void {
    this.wasmFingerprint.set_timezone(timezone)
  }

  /**
   * Get JavaScript injection script for fingerprint spoofing
   */
  getInjectionScript(): string {
    return this.wasmFingerprint.get_injection_script()
  }
}

// ============================================================================
// DOM Parser Class
// ============================================================================

/**
 * DOM parser for extracting content from HTML
 */
export class ThaloraDOM {
  private wasmDOM: WasmDOMType

  constructor(wasmModule: any, html: string) {
    this.wasmDOM = new wasmModule.WasmDOM(html)
  }

  /**
   * Get raw HTML
   */
  getHTML(): string {
    return this.wasmDOM.get_html()
  }

  /**
   * Get text content (tags stripped)
   */
  getText(): string {
    return this.wasmDOM.get_text()
  }

  /**
   * Get page title
   */
  getTitle(): string | null {
    return this.wasmDOM.get_title() ?? null
  }

  /**
   * Extract all links
   */
  getLinks(): Link[] {
    const links = this.wasmDOM.get_links()
    return links.map((l: WasmLink) => ({
      url: l.url,
      text: l.text,
    }))
  }
}

// ============================================================================
// Factory Function
// ============================================================================

/**
 * Create and initialize a ThaloraBrowser instance
 */
export async function createBrowser(
  config?: BrowserConfig
): Promise<ThaloraBrowser> {
  const browser = new ThaloraBrowser()
  await browser.initialize(config)
  return browser
}

// ============================================================================
// Utility Functions
// ============================================================================

/**
 * Format bytes to human-readable string
 */
export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(2)} KB`
  if (bytes < 1024 * 1024 * 1024)
    return `${(bytes / (1024 * 1024)).toFixed(2)} MB`
  return `${(bytes / (1024 * 1024 * 1024)).toFixed(2)} GB`
}

// Default export
export default ThaloraBrowser
